### ISSUE TITLE
Is there any provided code for extracting the specific QA pairs?

### ISSUE THREAD

**Issue by JulietLJY** [microsoft/RedStone#2]
The output of submit.py --network_path ./configs/cc_openquestion_filter.CC-MAIN-2023-23.json only reaches the filter part mentioned in the paper. The output is a subset of the input file paths, indicating that these files contain QA pairs. Is there any provided code for extracting the specific QA pairs afterwards?

**Comment by Dod-o** [comment]
Due to the loss of process files, we do not have the index corresponding to the QA data. We will be releasing the classifier weights soon, which we use to identify potential QA pairs.
